### ISSUE TITLE
unique_ptr + classes

### ISSUE THREAD

**Issue by p0nce** [Inochi2D/numem#1]
Hello,

- [x] `unique_ptr!A.get()` with A being a class, returns a `A*`. I had expected it to return a `A`. Same with `getAtomic()`, and same with `shared_ptr!A` and `weak_ptr!A` from a cursory reading. Not sure about `opCast`. If the RC pointer was a class instance in those cases, that also helps with inference. (currently ptr!class_instance is not `@safe`, the recent cast breaks inference)

- [x] I think `basic_string`'s `append_/set_/this(immutable(T)[] text)/opAssign/opOpAssign` are really meant to take a `const(char)[]` as input, since that data will be copied internally. 

- [x] I would prefer to just `import numem;`
Else it easily becomes:
```
import numem;
import numem.ptr;
import numem.string;
```
which I believe will be tiring pretty soon as `unique_ptr` will force user code to do at least two `import` quickly.

- [x] A pretty big one: `shared_ptr` can go in a `vector` but not `unique_ptr` (disabled postblit).
    It's a bit similar to C++98, where `std::auto_ptr` coudln't go into a `std::vector` but in C++11 `std::unique_ptr` could with mov semantics. Cope-out could perhaps be for vector to find a way to detect if some type is moveable or not.

**Comment by LunaTheFoxgirl** [comment]
- I've made so that unique, shared and weak ptr returns T instead of T* for classes,
- Basic string now takes const(char)[] for most things, with the exception of casting to D strings and using toDString.
- I've added `numem.all` as a shorthand to import all of numem, mainly to make it easier to opt in to importing everything for compilation speed's sake.

**Comment by p0nce** [comment]
Thanks!!
